apiVersion: v1
kind: ConfigMap
metadata:
  name: silencer-config
data:
  silencer.yml: |
    maintenances:
      - matchers:
          - "alertname=test"
        schedule: "6 * * * *"
        duration: "1s"

      - matchers:
          - "alertname=test2"
        schedule: "* * * * *"
        duration: "2s"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: silencer
spec:
  selector:
    matchLabels:
      app: silencer
  replicas: 1
  template:
    metadata:
      labels:
        app: silencer
    spec:
      containers:
        - name: silencer
          image: nwlunatic/prometheus-alertmanager-silencer:${IMAGE_VERSION}
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 25m
              memory: 10Mi
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: silencer-config-volume
              mountPath: /app/silencer.yml
              subPath: silencer.yml
          env:
            - name: ALERT_MANAGER_URL
              value: http://alertmanager:9093
            - name: CONFIG_FILE
              value: /app/silencer.yml
      volumes:
        - name: silencer-config-volume
          configMap:
            name: silencer-config
---
apiVersion: v1
kind: Service
metadata:
  name: silencer
spec:
  type: NodePort
  selector:
    app: silencer
  ports:
    - name: http
      port: 80
      targetPort: 5000
