name: CI

on:
  push

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: make docker-lint

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: make docker-test

  tests-with-infrastructure:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: up-infrastructure
        run: make up-infrastructure
      - name: tests-with-infrastructure
        run: make docker-tests-with-infrastructure

  build-and-push:
    runs-on: ubuntu-20.04

    needs: [ lint, test, tests-with-infrastructure ]
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: build-image
        run: make build-image

      - name: tag-image
        run: make tag-image

      - name: tag-image
        run: make push-image